apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv0005
    namespace: devpos
spec:
    capacity:
      storage: 1Gi
    accessModes:
      - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    nfs:
      path: /opt/pv-slave
      server: 192.168.3.208
