apiVersion: v1
kind: Service
metadata: 
  name: mysql-service
spec:
  ports:
  - protocol: TCP
    port: 33306
    targetPort: 3306
---
kind: Endpoints
apiVersion: v1
metadata:
  name: mysql-service
subsets:
- addresses:
  - ip: 192.168.3.139
  ports:
  - port: 3306
