apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
    spec:
      containers:
      - image: filebeat:v6.2.4
        imagePullPolicy: IfNotPresent
        name: filebeat
        volumeMounts:
        - name: app-logs
          mountPath: /log/app
        - name: pods-logs
          mountPath: /log/pods
        - name: filebeat-config
          mountPath: /etc/filebeat/
      volumes:
      - name: app-logs
        hostPath:
          path: /var/log/phicomm
      - name: pods-logs
        hostPath:
          path: /var/lib/docker/containers
      - name: filebeat-config
        configMap:
          name: filebeat-config

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
data:
  filebeat.yml: |-
    #=========================== Filebeat prospectors =============================
    filebeat.prospectors:
    # Each - is a prospector. Most options can be set at the prospector level, so
    # you can use different prospectors for various configurations.
    # Below are the prospector specific configurations.
    - type: log
      enabled: true
      paths:
        - /log/app/*/*.log
      multiline.pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      multiline.negate: true
      multiline.match: after
      multiline.timeout: 10s
      fields:
        env: dev-app
        log_topics: log-api

    - type: log
      enabled: false
      paths:
        - /log/pods/*/*.log
      multiline.pattern: '^{'
      multiline.negate: true
      multiline.match: after
      multiline.timeout: 10s
      fields:
        env: dev-pods
        log_topics: log-containers

    #============================= Filebeat modules ===============================
    
    filebeat.config.modules:
      # Glob pattern for configuration loading
      path: ${path.config}/modules.d/*.yml
    
      # Set to true to enable config reloading
      reload.enabled: false
    
      # Period on which files under path should be checked for changes
      #reload.period: 10s
    
    #==================== Elasticsearch template setting ==========================
    
    setup.template.settings:
      index.number_of_shards: 3
      #index.codec: best_compression
      #_source.enabled: false
    
    #================================ General =====================================
    
    # The name of the shipper that publishes the network data. It can be used to group
    # all the transactions sent by a single shipper in the web interface.
    #name:
    
    # The tags of the shipper are included in their own field with each
    # transaction published.
    #tags: ["service-X", "web-tier"]
    
    # Optional fields that you can specify to add additional information to the
    # output.
    fields:
      env: dev
    
    #============================== Kibana =====================================
    
    # Starting with Beats version 6.0.0, the dashboards are loaded via the Kibana API.
    # This requires a Kibana endpoint configuration.
    setup.kibana:
      host: "kibana-logging.kube-system:5601"
      # Kibana Host
      # Scheme and port can be left out and will be set to the default (http and 5601)
      # In case you specify and additional path, the scheme is required: http://localhost:5601/path
      # IPv6 addresses should always be defined as: https://[2001:db8::1]:5601
      #host: "localhost:5601"
    
    #================================ Outputs =====================================
    
    # Configure what output to use when sending the data collected by the beat.
    
    #-------------------------- Elasticsearch output ------------------------------
    #output.elasticsearch:
      # Array of hosts to connect to.
    #  hosts: ["elasticsearch-logging.kube-system:9200"]
    
      # Optional protocol and basic auth credentials.
      #protocol: "https"
      #username: "elastic"
      #password: "changeme"
    #------------------------kafka output ----------------------------------------
    output.kafka:
      hosts: ["kafka-svc.kube-system:9093"]
      topic: 'log-api'
      partition.round_robin:
        reachable_only: false
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000
