# cat dockerfile
FROM  docker.io/centos

# Install Filebeat
WORKDIR /usr/local
COPY filebeat-6.2.4-x86_64.rpm  /usr/local
RUN rpm -Uvh --replacepkgs /usr/local/filebeat-6.2.4-x86_64.rpm
ADD ./docker-entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/docker-entrypoint.sh

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["filebeat","-e","-c","/etc/filebeat/filebeat.yml"]
