apiVersion: v1
kind: LimitRange
metadata:
  name: res-kube-systme
  namespace: prod
spec:
  limits:
  - max:
      cpu: "4"
      memory: 16Gi
    min:
      cpu: 200m
      memory: 6Mi
    maxLimitRequestRatio:
      cpu: 3
      memory: 2
    type: Pod
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: 200m
      memory: 100Mi
    max:
      cpu: "2"
      memory: 4Gi
    min:
      cpu: 100m
      memory: 3Mi
    maxLimitRequestRatio:
      cpu: 5
      memory: 4
    type: Container
