apiVersion: v1
kind: Pod
metadata:
  labels:
    app: tt-0-app
  name: tt-0-app-0704
  namespace: prod
spec:
  containers:
  - env:
    - name: spring.profiles.active
      value: prod
    image: aigpu.phicomm.com:30143/library/tt-0:v2.1
    imagePullPolicy: IfNotPresent
    name: container
    resources:
      limits:
        cpu: 1
        memory: 200Mi
    ports:
    - containerPort: 8084
      protocol: TCP
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-ssh2k
      readOnly: true
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-ssh2k
    secret:
      defaultMode: 420
      secretName: default-token-ssh2k

