apiVersion: v1
kind: ResourceQuota
metadata:
  name: compute-resources
  namespace: dev
spec:
  hard:
    pods: "10"
    requests.cpu: "10"
    requests.memory: 20Gi
    limits.cpu: "20"
    limits.memory: 40Gi

---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-counts
  namespace: dev
spec:
  hard:
    configmaps: "20"
    persistentvolumeclaims: "20"
    replicationcontrollers: "20"
    secrets: "100"
    services: "20"
    services.loadbalancers: "2"
    services.nodeports: "10"
